// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2Bz1J7-eZZupIoh-dDNnKnde7WVDYK5U',
    appId: '1:250093281799:web:eb15c9ee6362ff3cd300a2',
    messagingSenderId: '250093281799',
    projectId: 'ai-study-1f43a',
    authDomain: 'ai-study-1f43a.firebaseapp.com',
    storageBucket: 'ai-study-1f43a.firebasestorage.app',
    measurementId: 'G-9WBWEQT75C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEDko5bs--r2X6vszLDUUMVNvp02rgQ0Q',
    appId: '1:250093281799:android:bfa97b62ff442a64d300a2',
    messagingSenderId: '250093281799',
    projectId: 'ai-study-1f43a',
    storageBucket: 'ai-study-1f43a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu3j4bA5aaktNUq9j4S8ZYCN8iclL7op0',
    appId: '1:250093281799:ios:ce15f5c11c0571a9d300a2',
    messagingSenderId: '250093281799',
    projectId: 'ai-study-1f43a',
    storageBucket: 'ai-study-1f43a.firebasestorage.app',
    iosBundleId: 'com.prashantkumar.aistudyassistant.aiStudyAssistant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBu3j4bA5aaktNUq9j4S8ZYCN8iclL7op0',
    appId: '1:250093281799:ios:ce15f5c11c0571a9d300a2',
    messagingSenderId: '250093281799',
    projectId: 'ai-study-1f43a',
    storageBucket: 'ai-study-1f43a.firebasestorage.app',
    iosBundleId: 'com.prashantkumar.aistudyassistant.aiStudyAssistant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2Bz1J7-eZZupIoh-dDNnKnde7WVDYK5U',
    appId: '1:250093281799:web:17e6d4158146db4fd300a2',
    messagingSenderId: '250093281799',
    projectId: 'ai-study-1f43a',
    authDomain: 'ai-study-1f43a.firebaseapp.com',
    storageBucket: 'ai-study-1f43a.firebasestorage.app',
    measurementId: 'G-P1W5XV2K12',
  );
}
